### ISSUE TITLE
Unable to see the menu or the UI controls

### ISSUE THREAD

**Issue by MidhunVarghese** [mrstampy/EntrainerFX#1]
Hi,
I stumbled upon this project when i was searching for Shimmer Animation (usually seen in Facebook when posts loads) for JavaFX. Me having read much about astral world and brainwaves took the liberty of downloading this project. 

When I open the program, after the splash screen disappears, the main window appears with the cosmic backgrounds but I was unable to see anything but the background itself unless I hover the mouse over each element.

**Comment by mrstampy** [comment]
Thanks for the interest. The program has been designed to work this way.
The included documentation can help to explain further. Cheers.

Burt.
